apiVersion: v1
kind: Pod
metadata:
  name: pending-pod123
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        memory: "5Gi" # Request more memory than available
    command: ["sleep", "3600"] # Sleep for an hour
